language: python
python:
  - "2.7"
  - "3.4"
env:
  - APP_SETTINGS=config.DevelopmentConfig
  - DATABASE_URL=postgres://postgres@localhost/atos
services:
  - postgresql
before_script:
  - psql -c 'create database atos;' -U postgres
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: python tests/algorithm-tests.py
