"""empty message

Revision ID: 11620a5779a3
Revises: 54a4253daca9
Create Date: 2016-04-10 21:15:13.669684

"""

# revision identifiers, used by Alembic.
revision = '11620a5779a3'
down_revision = '54a4253daca9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_matching',
    sa.Column('headcode', sa.String(length=20), nullable=False),
    sa.Column('origin_location', sa.String(length=20), nullable=False),
    sa.Column('origin_departure', sa.DateTime(), nullable=False),
    sa.Column('gps_car_id', sa.String(length=20), nullable=False),
    sa.Column('total_matching', sa.Integer(), nullable=False),
    sa.Column('median_time_error', sa.Float(), nullable=False),
    sa.Column('variance_time_error', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('headcode', 'origin_location', 'origin_departure', 'gps_car_id')
    )
    op.create_index('service_matching_service_lookup', 'service_matching', ['headcode', 'origin_location', 'origin_departure'], unique=False)
    op.create_index('service_matching_unit_lookup', 'service_matching', ['gps_car_id'], unique=False)
    op.alter_column(u'event_matching', 'time_error',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column(u'geographical_location', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=32),
               existing_nullable=True)
    op.alter_column(u'geographical_location', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=32),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'geographical_location', 'longitude',
               existing_type=sa.Float(precision=32),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column(u'geographical_location', 'latitude',
               existing_type=sa.Float(precision=32),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column(u'event_matching', 'time_error',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index('service_matching_unit_lookup', table_name='service_matching')
    op.drop_index('service_matching_service_lookup', table_name='service_matching')
    op.drop_table('service_matching')
    ### end Alembic commands ###
