"""empty message

Revision ID: 18b0c9c5513
Revises: 4c28d305a00
Create Date: 2016-04-15 23:23:05.645702

"""

# revision identifiers, used by Alembic.
revision = '18b0c9c5513'
down_revision = '4c28d305a00'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_matching', 'total_missed_in_between')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_matching', sa.Column('total_missed_in_between', sa.INTEGER(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
