"""empty message

Revision ID: 1da34d253b9a
Revises: 18b0c9c5513
Create Date: 2016-04-16 00:51:27.072201

"""

# revision identifiers, used by Alembic.
revision = '1da34d253b9a'
down_revision = '18b0c9c5513'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_matching')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_matching',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('headcode', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('origin_location', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('origin_departure', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('gps_car_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('trust_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gps_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gps_event_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('trust_event_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['gps_id'], [u'gps.id'], name=u'event_matching_gps_id_fkey'),
    sa.ForeignKeyConstraint(['trust_id'], [u'trust.id'], name=u'event_matching_trust_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'event_matching_pkey')
    )
    ### end Alembic commands ###
