"""empty message

Revision ID: 2234e6e644b8
Revises: 44dbee4e8cb0
Create Date: 2015-11-23 14:43:32.357627

"""

# revision identifiers, used by Alembic.
revision = '2234e6e644b8'
down_revision = '44dbee4e8cb0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gps', 'event_type',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=5),
               existing_nullable=True)
    op.alter_column('schedule', 'CIF_uid',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('schedule', 'headcode',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('schedule', 'unit',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('trust', 'CIF_uid',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('trust', 'category',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=5),
               existing_nullable=True)
    op.alter_column('trust', 'headcode',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('unit_to_gps_mapping', 'gps_car_id',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('unit_to_gps_mapping', 'unit',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=20))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unit_to_gps_mapping', 'unit',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=4))
    op.alter_column('unit_to_gps_mapping', 'gps_car_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('trust', 'headcode',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)
    op.alter_column('trust', 'category',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
    op.alter_column('trust', 'CIF_uid',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
    op.alter_column('schedule', 'unit',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)
    op.alter_column('schedule', 'headcode',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)
    op.alter_column('schedule', 'CIF_uid',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
    op.alter_column('gps', 'event_type',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)
    ### end Alembic commands ###
