"""empty message

Revision ID: 247b8442222b
Revises: 2234e6e644b8
Create Date: 2015-11-26 00:58:13.216021

"""

# revision identifiers, used by Alembic.
revision = '247b8442222b'
down_revision = '2234e6e644b8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('cif_uid', sa.String(length=20), nullable=True))
    op.add_column('schedule', sa.Column('origin_departure', sa.DateTime(), nullable=True))
    op.add_column('schedule', sa.Column('origin_location', sa.String(), nullable=True))
    op.drop_column('schedule', 'origin_loc')
    op.drop_column('schedule', 'CIF_uid')
    op.drop_column('schedule', 'origin_dep_time')
    op.add_column('trust', sa.Column('event_time', sa.DateTime(), nullable=True))
    op.add_column('trust', sa.Column('event_type', sa.String(length=5), nullable=True))
    op.add_column('trust', sa.Column('origin_departure', sa.DateTime(), nullable=True))
    op.add_column('trust', sa.Column('origin_location', sa.String(length=20), nullable=True))
    op.add_column('trust', sa.Column('planned_pass', sa.Boolean(), nullable=True))
    op.add_column('trust', sa.Column('seq', sa.Integer(), nullable=True))
    op.add_column('trust', sa.Column('tiploc', sa.String(length=20), nullable=True))
    op.drop_column('trust', 'category')
    op.drop_column('trust', 'dep_report')
    op.drop_column('trust', 'origin_depart_time')
    op.drop_column('trust', 'loc_seq')
    op.drop_column('trust', 'location')
    op.drop_column('trust', 'arrival_report')
    op.drop_column('trust', 'CIF_uid')
    op.drop_column('trust', 'planned')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trust', sa.Column('planned', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('trust', sa.Column('CIF_uid', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('trust', sa.Column('arrival_report', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('trust', sa.Column('location', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('trust', sa.Column('loc_seq', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trust', sa.Column('origin_depart_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('trust', sa.Column('dep_report', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('trust', sa.Column('category', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.drop_column('trust', 'tiploc')
    op.drop_column('trust', 'seq')
    op.drop_column('trust', 'planned_pass')
    op.drop_column('trust', 'origin_location')
    op.drop_column('trust', 'origin_departure')
    op.drop_column('trust', 'event_type')
    op.drop_column('trust', 'event_time')
    op.add_column('schedule', sa.Column('origin_dep_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('schedule', sa.Column('CIF_uid', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('schedule', sa.Column('origin_loc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('schedule', 'origin_location')
    op.drop_column('schedule', 'origin_departure')
    op.drop_column('schedule', 'cif_uid')
    ### end Alembic commands ###
