"""empty message

Revision ID: 27ee1ff60ebe
Revises: None
Create Date: 2015-11-15 15:58:16.683617

"""

# revision identifiers, used by Alembic.
revision = '27ee1ff60ebe'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=1), nullable=True),
    sa.Column('tiploc', sa.String(length=10), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=4), nullable=True),
    sa.Column('headcode', sa.String(length=4), nullable=True),
    sa.Column('origin_loc', sa.String(), nullable=True),
    sa.Column('origin_dep_time', sa.DateTime(), nullable=True),
    sa.Column('CIF_uid', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trust',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headcode', sa.String(length=4), nullable=True),
    sa.Column('location', sa.String(length=10), nullable=True),
    sa.Column('loc_seq', sa.Integer(), nullable=True),
    sa.Column('arrival_report', sa.DateTime(), nullable=True),
    sa.Column('dep_report', sa.DateTime(), nullable=True),
    sa.Column('planned', sa.Boolean(), nullable=True),
    sa.Column('origin_depart_time', sa.DateTime(), nullable=True),
    sa.Column('CIF_uid', sa.String(length=6), nullable=True),
    sa.Column('category', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_to_gps_mapping',
    sa.Column('unit', sa.String(length=4), nullable=False),
    sa.Column('gps_car_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('unit')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_to_gps_mapping')
    op.drop_table('trust')
    op.drop_table('schedule')
    op.drop_table('gps')
    ### end Alembic commands ###
