"""empty message

Revision ID: 3bf1357adaa3
Revises: 11620a5779a3
Create Date: 2016-04-10 23:01:18.625481

"""

# revision identifiers, used by Alembic.
revision = '3bf1357adaa3'
down_revision = '11620a5779a3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_matching', sa.Column('gps_event_time', sa.DateTime(), nullable=False))
    op.add_column('event_matching', sa.Column('trust_event_time', sa.DateTime(), nullable=False))
    op.drop_column('event_matching', 'time_error')
    op.alter_column('geographical_location', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=32),
               existing_nullable=True)
    op.alter_column('geographical_location', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=32),
               existing_nullable=True)
    op.add_column('service_matching', sa.Column('end', sa.DateTime(), nullable=False))
    op.add_column('service_matching', sa.Column('start', sa.DateTime(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_matching', 'start')
    op.drop_column('service_matching', 'end')
    op.alter_column('geographical_location', 'longitude',
               existing_type=sa.Float(precision=32),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('geographical_location', 'latitude',
               existing_type=sa.Float(precision=32),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.add_column('event_matching', sa.Column('time_error', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('event_matching', 'trust_event_time')
    op.drop_column('event_matching', 'gps_event_time')
    ### end Alembic commands ###
