"""empty message

Revision ID: 4b29c2a22cbf
Revises: 42eaacf9f9bb
Create Date: 2016-02-10 16:48:15.642618

"""

# revision identifiers, used by Alembic.
revision = '4b29c2a22cbf'
down_revision = '42eaacf9f9bb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diagram_stop', 'diagram_service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('geographical_location', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=32),
               existing_nullable=True)
    op.alter_column('geographical_location', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=32),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('geographical_location', 'longitude',
               existing_type=sa.Float(precision=32),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('geographical_location', 'latitude',
               existing_type=sa.Float(precision=32),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('diagram_stop', 'diagram_service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
