"""empty message

Revision ID: 4c28d305a00
Revises: 19f7b53eee51
Create Date: 2016-04-15 15:02:43.790051

"""

# revision identifiers, used by Alembic.
revision = '4c28d305a00'
down_revision = '19f7b53eee51'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_matching', sa.Column('mean_time_error', sa.Float(), nullable=False))
    op.add_column('service_matching', sa.Column('variance_time_error', sa.Float(), nullable=False))
    op.drop_column('service_matching', 'median_time_error')
    op.drop_column('service_matching', 'iqr_time_error')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_matching', sa.Column('iqr_time_error', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('service_matching', sa.Column('median_time_error', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('service_matching', 'variance_time_error')
    op.drop_column('service_matching', 'mean_time_error')
    ### end Alembic commands ###
