"""empty message

Revision ID: 54a4253daca9
Revises: 5511e24af80f
Create Date: 2016-04-10 17:13:01.748990

"""

# revision identifiers, used by Alembic.
revision = '54a4253daca9'
down_revision = '5511e24af80f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_matching',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headcode', sa.String(length=20), nullable=True),
    sa.Column('origin_location', sa.String(length=20), nullable=True),
    sa.Column('origin_departure', sa.DateTime(), nullable=True),
    sa.Column('gps_car_id', sa.String(length=20), nullable=True),
    sa.Column('trust_id', sa.Integer(), nullable=False),
    sa.Column('gps_id', sa.Integer(), nullable=False),
    sa.Column('time_error', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['gps_id'], ['gps.id'], ),
    sa.ForeignKeyConstraint(['trust_id'], ['trust.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('event_matching_service_lookup', 'event_matching', ['headcode', 'origin_location', 'origin_departure'], unique=False)
    op.create_index('event_matching_unit_lookup', 'event_matching', ['gps_car_id'], unique=False)
    op.alter_column(u'geographical_location', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=32),
               existing_nullable=True)
    op.alter_column(u'geographical_location', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=32),
               existing_nullable=True)
    op.create_index(op.f('ix_gps_gps_car_id'), 'gps', ['gps_car_id'], unique=False)
    op.create_index('trust_service_lookup', 'trust', ['headcode', 'origin_location', 'origin_departure'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('trust_service_lookup', table_name='trust')
    op.drop_index(op.f('ix_gps_gps_car_id'), table_name='gps')
    op.alter_column(u'geographical_location', 'longitude',
               existing_type=sa.Float(precision=32),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column(u'geographical_location', 'latitude',
               existing_type=sa.Float(precision=32),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_index('event_matching_unit_lookup', table_name='event_matching')
    op.drop_index('event_matching_service_lookup', table_name='event_matching')
    op.drop_table('event_matching')
    ### end Alembic commands ###
